name: DS5111 Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Inspection (Linter)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check Python Version
        run: python --version
      - name: Install pipeline dependencies
        run: make update
      - name: Lint codebase with Pylint
        run: make lint

  test:
    name: Unit Testing Engine (Pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check Python Version
        run: python --version
      - name: Install pipeline dependencies
        run: make update
      - name: Execute automated test suite with Pytest
        run: make test
